package com.configx.web.dao;

import com.configx.web.model.BuildConfigChange;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BuildConfigChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_config_change
     *
     * @mbggenerated
     */
    int insert(BuildConfigChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build_config_change
     *
     * @mbggenerated
     */
    int insertSelective(BuildConfigChange record);

    List<BuildConfigChange> selectChangesByBuildId(@Param("buildId") long buildId);

    List<BuildConfigChange> selectChanges(@Param("appId") int appId, @Param("envId") int envId, @Param("lastBuildId") long lastBuildId, @Param("buildId") long buildId);
}