package com.configx.web.dao;

import com.configx.web.model.Build;

public interface BuildMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated
     */
    int insert(Build record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated
     */
    int insertSelective(Build record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated
     */
    Build selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Build record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table build
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Build record);
}