package com.configx.web.dao;

import com.configx.web.model.ConfigItemHistory;
import com.configx.web.param.HistorySearchParam;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ConfigItemHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_item_history
     *
     * @mbggenerated
     */
    int insert(ConfigItemHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_item_history
     *
     * @mbggenerated
     */
    int insertSelective(ConfigItemHistory record);

    ConfigItemHistory getByConfigRevision(@Param("configId") long configId, @Param("revision") long revision);

    ConfigItemHistory getByConfigNameRevision(@Param("configName") String configName, @Param("revision") long revision);

    List<ConfigItemHistory> getByRevision(long revision);

    List<ConfigItemHistory> getByRevisions(List<Long> revisions);

    List<ConfigItemHistory> getByRevisionRange(@Param("appId") int appId, @Param("envId") int envId, @Param("from") long from, @Param("to") long to);

    List<ConfigItemHistory> getByAppId(int appId);

    List<ConfigItemHistory> getByAppAndEnv(@Param("appId") Integer appId, @Param("envId") Integer envId);

    List<ConfigItemHistory> getByConfigId(@Param("configId") Long configId);

    List<ConfigItemHistory> getByConfigName(@Param("configName") String configName);

    int countForSearch(HistorySearchParam param);

    List<ConfigItemHistory> search(HistorySearchParam param);

}