package com.configx.web.dao;

import java.util.Date;
import java.util.List;

import com.configx.web.model.ConfigItem;
import org.apache.ibatis.annotations.Param;

public interface ConfigItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_item
     *
     * @mbggenerated
     */
    int insert(ConfigItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_item
     *
     * @mbggenerated
     */
    int insertSelective(ConfigItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_item
     *
     * @mbggenerated
     */
    ConfigItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConfigItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ConfigItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConfigItem record);

    int updateRevisionInfo(@Param("id") long id, @Param("revision") long revision, @Param("dataChangeLastTime") Date dataChangeLastTime);

    List<ConfigItem> selectByIds(List<Long> idList);

    List<ConfigItem> selectByApp(@Param("appId") Integer appId);

    List<ConfigItem> selectByAppEnv(@Param("appId") Integer appId, @Param("envId") Integer envId);

    List<ConfigItem> selectByAppEnvProfileList(@Param("appId") Integer appId, @Param("envId") Integer envId, @Param("profileIdList") List<Integer> profileIdList);
}