package com.configx.web.dao;

import com.configx.web.model.ConfigCommit;
import com.configx.web.param.CommitSearchParam;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ConfigCommitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_commit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long revision);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_commit
     *
     * @mbggenerated
     */
    int insert(ConfigCommit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_commit
     *
     * @mbggenerated
     */
    int insertSelective(ConfigCommit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_commit
     *
     * @mbggenerated
     */
    ConfigCommit selectByPrimaryKey(Long revision);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_commit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConfigCommit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_commit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConfigCommit record);

    List<ConfigCommit> selectByAppEnv(@Param("appId") Integer appId, @Param("envId") Integer envId);

    List<ConfigCommit> selectByIds(List<Long> revisionList);

    int countForSearch(CommitSearchParam param);

    List<ConfigCommit> search(CommitSearchParam param);
}