package com.configx.web.dao;

import java.util.List;

import com.configx.web.model.ConfigValue;

public interface ConfigValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_value
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_value
     *
     * @mbggenerated
     */
    int insert(ConfigValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_value
     *
     * @mbggenerated
     */
    int insertSelective(ConfigValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_value
     *
     * @mbggenerated
     */
    ConfigValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_value
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConfigValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_value
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ConfigValue record);

    List<ConfigValue> getByIdList(List<Long> idList);
}