package com.configx.web.dao;

import java.util.List;

import com.configx.web.model.Env;

public interface EnvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbggenerated
     */
    int insert(Env record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbggenerated
     */
    int insertSelective(Env record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbggenerated
     */
    Env selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Env record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Env record);
    
    List<Env> selectByAppId(Integer appId);
}