package com.configx.web.dao;

import com.configx.web.model.ReleaseForm;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ReleaseFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_form
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_form
     *
     * @mbggenerated
     */
    int insert(ReleaseForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_form
     *
     * @mbggenerated
     */
    int insertSelective(ReleaseForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_form
     *
     * @mbggenerated
     */
    ReleaseForm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_form
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReleaseForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_form
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReleaseForm record);

    List<ReleaseForm> selectByLowLimitId(@Param("lowLimitId") long LowLimitId, @Param("count") int count);

    List<ReleaseForm> selectByUpLimitId(@Param("upLimitId") long upLimitId, @Param("count") int count);

    List<ReleaseForm> selectByAppId(@Param("appId") int appId);

    List<ReleaseForm> selectByEnvId(@Param("appId") int appId, @Param("envId") int envId);

    ReleaseForm getLastForm(@Param("appId") int appId, @Param("envId") int envId, @Param("id") long id);
}