package com.configx.web.dao;

import com.configx.web.model.Session;

public interface SessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated
     */
    int insert(Session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated
     */
    int insertSelective(Session record);

    int delete(String email);

    Session getByEmail(String email);
}