package com.configx.web.dao;

import com.configx.web.model.WebhookLog;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WebhookLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook_log
     *
     * @mbggenerated
     */
    int insert(WebhookLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook_log
     *
     * @mbggenerated
     */
    int insertSelective(WebhookLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook_log
     *
     * @mbggenerated
     */
    WebhookLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WebhookLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WebhookLog record);

    List<WebhookLog> selectByAppId(int appId);

    List<WebhookLog> selectByWebhookId(int webhookId);

    List<WebhookLog> selectByWebhookIdAndEventType(@Param("webhookId") int webhookId, @Param("eventType") int eventType);
}