package com.configx.web.dao;

import com.configx.web.model.WebhookEventParam;

import java.util.List;

public interface WebhookEventParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook_event_param
     *
     * @mbggenerated
     */
    int insert(WebhookEventParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook_event_param
     *
     * @mbggenerated
     */
    int insertSelective(WebhookEventParam record);

    /**
     * 批量插入
     *
     * @param records
     * @return
     */
    int batchInsert(List<WebhookEventParam> records);

    int deleteByWebhookId(int webhookId);

    List<WebhookEventParam> selectByWebhookIdList(List<Integer> webhookIdList);
}