package com.configx.web.dao;

import com.configx.web.model.Webhook;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WebhookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook
     *
     * @mbggenerated
     */
    int insert(Webhook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook
     *
     * @mbggenerated
     */
    int insertSelective(Webhook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook
     *
     * @mbggenerated
     */
    Webhook selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Webhook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Webhook record);

    List<Webhook> selectByAppId(int appId);

    List<Webhook> selectByAppAndEvent(@Param("appId") int appId, @Param("eventType") int eventType);
}