package com.configx.web.model;

public class BuildConfigChange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_change.build_id
     *
     * @mbggenerated
     */
    private Long buildId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_change.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_change.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_change.env_id
     *
     * @mbggenerated
     */
    private Integer envId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_change.env_name
     *
     * @mbggenerated
     */
    private String envName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_change.profile_id
     *
     * @mbggenerated
     */
    private Integer profileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_change.profile_name
     *
     * @mbggenerated
     */
    private String profileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_change.config_id
     *
     * @mbggenerated
     */
    private Long configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_change.config_name
     *
     * @mbggenerated
     */
    private String configName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_change.build_id
     *
     * @return the value of build_config_change.build_id
     *
     * @mbggenerated
     */
    public Long getBuildId() {
        return buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_change.build_id
     *
     * @param buildId the value for build_config_change.build_id
     *
     * @mbggenerated
     */
    public void setBuildId(Long buildId) {
        this.buildId = buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_change.app_id
     *
     * @return the value of build_config_change.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_change.app_id
     *
     * @param appId the value for build_config_change.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_change.app_name
     *
     * @return the value of build_config_change.app_name
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_change.app_name
     *
     * @param appName the value for build_config_change.app_name
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_change.env_id
     *
     * @return the value of build_config_change.env_id
     *
     * @mbggenerated
     */
    public Integer getEnvId() {
        return envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_change.env_id
     *
     * @param envId the value for build_config_change.env_id
     *
     * @mbggenerated
     */
    public void setEnvId(Integer envId) {
        this.envId = envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_change.env_name
     *
     * @return the value of build_config_change.env_name
     *
     * @mbggenerated
     */
    public String getEnvName() {
        return envName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_change.env_name
     *
     * @param envName the value for build_config_change.env_name
     *
     * @mbggenerated
     */
    public void setEnvName(String envName) {
        this.envName = envName == null ? null : envName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_change.profile_id
     *
     * @return the value of build_config_change.profile_id
     *
     * @mbggenerated
     */
    public Integer getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_change.profile_id
     *
     * @param profileId the value for build_config_change.profile_id
     *
     * @mbggenerated
     */
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_change.profile_name
     *
     * @return the value of build_config_change.profile_name
     *
     * @mbggenerated
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_change.profile_name
     *
     * @param profileName the value for build_config_change.profile_name
     *
     * @mbggenerated
     */
    public void setProfileName(String profileName) {
        this.profileName = profileName == null ? null : profileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_change.config_id
     *
     * @return the value of build_config_change.config_id
     *
     * @mbggenerated
     */
    public Long getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_change.config_id
     *
     * @param configId the value for build_config_change.config_id
     *
     * @mbggenerated
     */
    public void setConfigId(Long configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_change.config_name
     *
     * @return the value of build_config_change.config_name
     *
     * @mbggenerated
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_change.config_name
     *
     * @param configName the value for build_config_change.config_name
     *
     * @mbggenerated
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }
}