package com.configx.web.model;

public class BuildConfigItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_item.build_id
     *
     * @mbggenerated
     */
    private Long buildId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_item.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_item.env_id
     *
     * @mbggenerated
     */
    private Integer envId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_item.profile_id
     *
     * @mbggenerated
     */
    private Integer profileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_item.revision
     *
     * @mbggenerated
     */
    private Long revision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_item.config_id
     *
     * @mbggenerated
     */
    private Long configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_item.config_name
     *
     * @mbggenerated
     */
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_item.config_value_id
     *
     * @mbggenerated
     */
    private Long configValueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_item.config_tags
     *
     * @mbggenerated
     */
    private String configTags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build_config_item.config_value
     *
     * @mbggenerated
     */
    private String configValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_item.build_id
     *
     * @return the value of build_config_item.build_id
     *
     * @mbggenerated
     */
    public Long getBuildId() {
        return buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_item.build_id
     *
     * @param buildId the value for build_config_item.build_id
     *
     * @mbggenerated
     */
    public void setBuildId(Long buildId) {
        this.buildId = buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_item.app_id
     *
     * @return the value of build_config_item.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_item.app_id
     *
     * @param appId the value for build_config_item.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_item.env_id
     *
     * @return the value of build_config_item.env_id
     *
     * @mbggenerated
     */
    public Integer getEnvId() {
        return envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_item.env_id
     *
     * @param envId the value for build_config_item.env_id
     *
     * @mbggenerated
     */
    public void setEnvId(Integer envId) {
        this.envId = envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_item.profile_id
     *
     * @return the value of build_config_item.profile_id
     *
     * @mbggenerated
     */
    public Integer getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_item.profile_id
     *
     * @param profileId the value for build_config_item.profile_id
     *
     * @mbggenerated
     */
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_item.revision
     *
     * @return the value of build_config_item.revision
     *
     * @mbggenerated
     */
    public Long getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_item.revision
     *
     * @param revision the value for build_config_item.revision
     *
     * @mbggenerated
     */
    public void setRevision(Long revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_item.config_id
     *
     * @return the value of build_config_item.config_id
     *
     * @mbggenerated
     */
    public Long getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_item.config_id
     *
     * @param configId the value for build_config_item.config_id
     *
     * @mbggenerated
     */
    public void setConfigId(Long configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_item.config_name
     *
     * @return the value of build_config_item.config_name
     *
     * @mbggenerated
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_item.config_name
     *
     * @param configName the value for build_config_item.config_name
     *
     * @mbggenerated
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_item.config_value_id
     *
     * @return the value of build_config_item.config_value_id
     *
     * @mbggenerated
     */
    public Long getConfigValueId() {
        return configValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_item.config_value_id
     *
     * @param configValueId the value for build_config_item.config_value_id
     *
     * @mbggenerated
     */
    public void setConfigValueId(Long configValueId) {
        this.configValueId = configValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_item.config_tags
     *
     * @return the value of build_config_item.config_tags
     *
     * @mbggenerated
     */
    public String getConfigTags() {
        return configTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_item.config_tags
     *
     * @param configTags the value for build_config_item.config_tags
     *
     * @mbggenerated
     */
    public void setConfigTags(String configTags) {
        this.configTags = configTags == null ? null : configTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build_config_item.config_value
     *
     * @return the value of build_config_item.config_value
     *
     * @mbggenerated
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build_config_item.config_value
     *
     * @param configValue the value for build_config_item.config_value
     *
     * @mbggenerated
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }
}