package com.configx.web.model;

import java.util.Date;

public class Build {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.last_id
     *
     * @mbggenerated
     */
    private Long lastId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.env_id
     *
     * @mbggenerated
     */
    private Integer envId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.env_name
     *
     * @mbggenerated
     */
    private String envName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.revision
     *
     * @mbggenerated
     */
    private Long revision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column build.build_time
     *
     * @mbggenerated
     */
    private Date buildTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.id
     *
     * @return the value of build.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.id
     *
     * @param id the value for build.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.last_id
     *
     * @return the value of build.last_id
     *
     * @mbggenerated
     */
    public Long getLastId() {
        return lastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.last_id
     *
     * @param lastId the value for build.last_id
     *
     * @mbggenerated
     */
    public void setLastId(Long lastId) {
        this.lastId = lastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.app_id
     *
     * @return the value of build.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.app_id
     *
     * @param appId the value for build.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.app_name
     *
     * @return the value of build.app_name
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.app_name
     *
     * @param appName the value for build.app_name
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.env_id
     *
     * @return the value of build.env_id
     *
     * @mbggenerated
     */
    public Integer getEnvId() {
        return envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.env_id
     *
     * @param envId the value for build.env_id
     *
     * @mbggenerated
     */
    public void setEnvId(Integer envId) {
        this.envId = envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.env_name
     *
     * @return the value of build.env_name
     *
     * @mbggenerated
     */
    public String getEnvName() {
        return envName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.env_name
     *
     * @param envName the value for build.env_name
     *
     * @mbggenerated
     */
    public void setEnvName(String envName) {
        this.envName = envName == null ? null : envName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.revision
     *
     * @return the value of build.revision
     *
     * @mbggenerated
     */
    public Long getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.revision
     *
     * @param revision the value for build.revision
     *
     * @mbggenerated
     */
    public void setRevision(Long revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column build.build_time
     *
     * @return the value of build.build_time
     *
     * @mbggenerated
     */
    public Date getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column build.build_time
     *
     * @param buildTime the value for build.build_time
     *
     * @mbggenerated
     */
    public void setBuildTime(Date buildTime) {
        this.buildTime = buildTime;
    }
}