package com.configx.web.model;

import java.util.Date;

public class ConfigItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.env_id
     *
     * @mbggenerated
     */
    private Integer envId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.profile_id
     *
     * @mbggenerated
     */
    private Integer profileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.value_id
     *
     * @mbggenerated
     */
    private Long valueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.value_type
     *
     * @mbggenerated
     */
    private Byte valueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.tags
     *
     * @mbggenerated
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.enable
     *
     * @mbggenerated
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.revision
     *
     * @mbggenerated
     */
    private Long revision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.last_revision
     *
     * @mbggenerated
     */
    private Long lastRevision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.data_change_last_time
     *
     * @mbggenerated
     */
    private Date dataChangeLastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.id
     *
     * @return the value of config_item.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.id
     *
     * @param id the value for config_item.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.app_id
     *
     * @return the value of config_item.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.app_id
     *
     * @param appId the value for config_item.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.env_id
     *
     * @return the value of config_item.env_id
     *
     * @mbggenerated
     */
    public Integer getEnvId() {
        return envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.env_id
     *
     * @param envId the value for config_item.env_id
     *
     * @mbggenerated
     */
    public void setEnvId(Integer envId) {
        this.envId = envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.profile_id
     *
     * @return the value of config_item.profile_id
     *
     * @mbggenerated
     */
    public Integer getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.profile_id
     *
     * @param profileId the value for config_item.profile_id
     *
     * @mbggenerated
     */
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.name
     *
     * @return the value of config_item.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.name
     *
     * @param name the value for config_item.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.value_id
     *
     * @return the value of config_item.value_id
     *
     * @mbggenerated
     */
    public Long getValueId() {
        return valueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.value_id
     *
     * @param valueId the value for config_item.value_id
     *
     * @mbggenerated
     */
    public void setValueId(Long valueId) {
        this.valueId = valueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.value_type
     *
     * @return the value of config_item.value_type
     *
     * @mbggenerated
     */
    public Byte getValueType() {
        return valueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.value_type
     *
     * @param valueType the value for config_item.value_type
     *
     * @mbggenerated
     */
    public void setValueType(Byte valueType) {
        this.valueType = valueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.tags
     *
     * @return the value of config_item.tags
     *
     * @mbggenerated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.tags
     *
     * @param tags the value for config_item.tags
     *
     * @mbggenerated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.description
     *
     * @return the value of config_item.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.description
     *
     * @param description the value for config_item.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.enable
     *
     * @return the value of config_item.enable
     *
     * @mbggenerated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.enable
     *
     * @param enable the value for config_item.enable
     *
     * @mbggenerated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.creator
     *
     * @return the value of config_item.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.creator
     *
     * @param creator the value for config_item.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.create_time
     *
     * @return the value of config_item.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.create_time
     *
     * @param createTime the value for config_item.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.updater
     *
     * @return the value of config_item.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.updater
     *
     * @param updater the value for config_item.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.update_time
     *
     * @return the value of config_item.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.update_time
     *
     * @param updateTime the value for config_item.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.revision
     *
     * @return the value of config_item.revision
     *
     * @mbggenerated
     */
    public Long getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.revision
     *
     * @param revision the value for config_item.revision
     *
     * @mbggenerated
     */
    public void setRevision(Long revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.last_revision
     *
     * @return the value of config_item.last_revision
     *
     * @mbggenerated
     */
    public Long getLastRevision() {
        return lastRevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.last_revision
     *
     * @param lastRevision the value for config_item.last_revision
     *
     * @mbggenerated
     */
    public void setLastRevision(Long lastRevision) {
        this.lastRevision = lastRevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.data_change_last_time
     *
     * @return the value of config_item.data_change_last_time
     *
     * @mbggenerated
     */
    public Date getDataChangeLastTime() {
        return dataChangeLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.data_change_last_time
     *
     * @param dataChangeLastTime the value for config_item.data_change_last_time
     *
     * @mbggenerated
     */
    public void setDataChangeLastTime(Date dataChangeLastTime) {
        this.dataChangeLastTime = dataChangeLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item.value
     *
     * @return the value of config_item.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item.value
     *
     * @param value the value for config_item.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}