package com.configx.web.model;

import java.util.Date;

public class ConfigCommit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_commit.revision
     *
     * @mbggenerated
     */
    private Long revision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_commit.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_commit.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_commit.env_id
     *
     * @mbggenerated
     */
    private Integer envId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_commit.env_name
     *
     * @mbggenerated
     */
    private String envName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_commit.profile_id
     *
     * @mbggenerated
     */
    private Integer profileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_commit.profile_name
     *
     * @mbggenerated
     */
    private String profileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_commit.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_commit.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_commit.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_commit.revision
     *
     * @return the value of config_commit.revision
     *
     * @mbggenerated
     */
    public Long getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_commit.revision
     *
     * @param revision the value for config_commit.revision
     *
     * @mbggenerated
     */
    public void setRevision(Long revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_commit.app_id
     *
     * @return the value of config_commit.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_commit.app_id
     *
     * @param appId the value for config_commit.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_commit.app_name
     *
     * @return the value of config_commit.app_name
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_commit.app_name
     *
     * @param appName the value for config_commit.app_name
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_commit.env_id
     *
     * @return the value of config_commit.env_id
     *
     * @mbggenerated
     */
    public Integer getEnvId() {
        return envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_commit.env_id
     *
     * @param envId the value for config_commit.env_id
     *
     * @mbggenerated
     */
    public void setEnvId(Integer envId) {
        this.envId = envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_commit.env_name
     *
     * @return the value of config_commit.env_name
     *
     * @mbggenerated
     */
    public String getEnvName() {
        return envName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_commit.env_name
     *
     * @param envName the value for config_commit.env_name
     *
     * @mbggenerated
     */
    public void setEnvName(String envName) {
        this.envName = envName == null ? null : envName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_commit.profile_id
     *
     * @return the value of config_commit.profile_id
     *
     * @mbggenerated
     */
    public Integer getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_commit.profile_id
     *
     * @param profileId the value for config_commit.profile_id
     *
     * @mbggenerated
     */
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_commit.profile_name
     *
     * @return the value of config_commit.profile_name
     *
     * @mbggenerated
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_commit.profile_name
     *
     * @param profileName the value for config_commit.profile_name
     *
     * @mbggenerated
     */
    public void setProfileName(String profileName) {
        this.profileName = profileName == null ? null : profileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_commit.author
     *
     * @return the value of config_commit.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_commit.author
     *
     * @param author the value for config_commit.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_commit.date
     *
     * @return the value of config_commit.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_commit.date
     *
     * @param date the value for config_commit.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_commit.message
     *
     * @return the value of config_commit.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_commit.message
     *
     * @param message the value for config_commit.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}