package com.configx.web.model;

import java.util.Date;

public class ConfigItemHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item_history.revision
     *
     * @mbggenerated
     */
    private Long revision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item_history.last_revision
     *
     * @mbggenerated
     */
    private Long lastRevision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item_history.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item_history.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item_history.env_id
     *
     * @mbggenerated
     */
    private Integer envId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item_history.env_name
     *
     * @mbggenerated
     */
    private String envName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item_history.profile_id
     *
     * @mbggenerated
     */
    private Integer profileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item_history.profile_name
     *
     * @mbggenerated
     */
    private String profileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item_history.config_id
     *
     * @mbggenerated
     */
    private Long configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item_history.config_name
     *
     * @mbggenerated
     */
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item_history.config_value_id
     *
     * @mbggenerated
     */
    private Long configValueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item_history.config_value_type
     *
     * @mbggenerated
     */
    private Byte configValueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item_history.config_tags
     *
     * @mbggenerated
     */
    private String configTags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item_history.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_item_history.config_value
     *
     * @mbggenerated
     */
    private String configValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item_history.revision
     *
     * @return the value of config_item_history.revision
     *
     * @mbggenerated
     */
    public Long getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item_history.revision
     *
     * @param revision the value for config_item_history.revision
     *
     * @mbggenerated
     */
    public void setRevision(Long revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item_history.last_revision
     *
     * @return the value of config_item_history.last_revision
     *
     * @mbggenerated
     */
    public Long getLastRevision() {
        return lastRevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item_history.last_revision
     *
     * @param lastRevision the value for config_item_history.last_revision
     *
     * @mbggenerated
     */
    public void setLastRevision(Long lastRevision) {
        this.lastRevision = lastRevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item_history.app_id
     *
     * @return the value of config_item_history.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item_history.app_id
     *
     * @param appId the value for config_item_history.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item_history.app_name
     *
     * @return the value of config_item_history.app_name
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item_history.app_name
     *
     * @param appName the value for config_item_history.app_name
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item_history.env_id
     *
     * @return the value of config_item_history.env_id
     *
     * @mbggenerated
     */
    public Integer getEnvId() {
        return envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item_history.env_id
     *
     * @param envId the value for config_item_history.env_id
     *
     * @mbggenerated
     */
    public void setEnvId(Integer envId) {
        this.envId = envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item_history.env_name
     *
     * @return the value of config_item_history.env_name
     *
     * @mbggenerated
     */
    public String getEnvName() {
        return envName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item_history.env_name
     *
     * @param envName the value for config_item_history.env_name
     *
     * @mbggenerated
     */
    public void setEnvName(String envName) {
        this.envName = envName == null ? null : envName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item_history.profile_id
     *
     * @return the value of config_item_history.profile_id
     *
     * @mbggenerated
     */
    public Integer getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item_history.profile_id
     *
     * @param profileId the value for config_item_history.profile_id
     *
     * @mbggenerated
     */
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item_history.profile_name
     *
     * @return the value of config_item_history.profile_name
     *
     * @mbggenerated
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item_history.profile_name
     *
     * @param profileName the value for config_item_history.profile_name
     *
     * @mbggenerated
     */
    public void setProfileName(String profileName) {
        this.profileName = profileName == null ? null : profileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item_history.config_id
     *
     * @return the value of config_item_history.config_id
     *
     * @mbggenerated
     */
    public Long getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item_history.config_id
     *
     * @param configId the value for config_item_history.config_id
     *
     * @mbggenerated
     */
    public void setConfigId(Long configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item_history.config_name
     *
     * @return the value of config_item_history.config_name
     *
     * @mbggenerated
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item_history.config_name
     *
     * @param configName the value for config_item_history.config_name
     *
     * @mbggenerated
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item_history.config_value_id
     *
     * @return the value of config_item_history.config_value_id
     *
     * @mbggenerated
     */
    public Long getConfigValueId() {
        return configValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item_history.config_value_id
     *
     * @param configValueId the value for config_item_history.config_value_id
     *
     * @mbggenerated
     */
    public void setConfigValueId(Long configValueId) {
        this.configValueId = configValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item_history.config_value_type
     *
     * @return the value of config_item_history.config_value_type
     *
     * @mbggenerated
     */
    public Byte getConfigValueType() {
        return configValueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item_history.config_value_type
     *
     * @param configValueType the value for config_item_history.config_value_type
     *
     * @mbggenerated
     */
    public void setConfigValueType(Byte configValueType) {
        this.configValueType = configValueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item_history.config_tags
     *
     * @return the value of config_item_history.config_tags
     *
     * @mbggenerated
     */
    public String getConfigTags() {
        return configTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item_history.config_tags
     *
     * @param configTags the value for config_item_history.config_tags
     *
     * @mbggenerated
     */
    public void setConfigTags(String configTags) {
        this.configTags = configTags == null ? null : configTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item_history.create_time
     *
     * @return the value of config_item_history.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item_history.create_time
     *
     * @param createTime the value for config_item_history.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_item_history.config_value
     *
     * @return the value of config_item_history.config_value
     *
     * @mbggenerated
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_item_history.config_value
     *
     * @param configValue the value for config_item_history.config_value
     *
     * @mbggenerated
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }
}