package com.configx.web.model;

import java.util.Date;

public class Env {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.alias
     *
     * @mbggenerated
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.order
     *
     * @mbggenerated
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.revision
     *
     * @mbggenerated
     */
    private Long revision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.data_change_last_time
     *
     * @mbggenerated
     */
    private Date dataChangeLastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.build_id
     *
     * @mbggenerated
     */
    private Long buildId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.build_time
     *
     * @mbggenerated
     */
    private Date buildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.release_version
     *
     * @mbggenerated
     */
    private Long releaseVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.release_time
     *
     * @mbggenerated
     */
    private Date releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.auto_release
     *
     * @mbggenerated
     */
    private Boolean autoRelease;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.id
     *
     * @return the value of env.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.id
     *
     * @param id the value for env.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.app_id
     *
     * @return the value of env.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.app_id
     *
     * @param appId the value for env.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.name
     *
     * @return the value of env.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.name
     *
     * @param name the value for env.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.alias
     *
     * @return the value of env.alias
     *
     * @mbggenerated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.alias
     *
     * @param alias the value for env.alias
     *
     * @mbggenerated
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.description
     *
     * @return the value of env.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.description
     *
     * @param description the value for env.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.order
     *
     * @return the value of env.order
     *
     * @mbggenerated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.order
     *
     * @param order the value for env.order
     *
     * @mbggenerated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.creator
     *
     * @return the value of env.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.creator
     *
     * @param creator the value for env.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.create_time
     *
     * @return the value of env.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.create_time
     *
     * @param createTime the value for env.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.updater
     *
     * @return the value of env.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.updater
     *
     * @param updater the value for env.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.update_time
     *
     * @return the value of env.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.update_time
     *
     * @param updateTime the value for env.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.revision
     *
     * @return the value of env.revision
     *
     * @mbggenerated
     */
    public Long getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.revision
     *
     * @param revision the value for env.revision
     *
     * @mbggenerated
     */
    public void setRevision(Long revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.data_change_last_time
     *
     * @return the value of env.data_change_last_time
     *
     * @mbggenerated
     */
    public Date getDataChangeLastTime() {
        return dataChangeLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.data_change_last_time
     *
     * @param dataChangeLastTime the value for env.data_change_last_time
     *
     * @mbggenerated
     */
    public void setDataChangeLastTime(Date dataChangeLastTime) {
        this.dataChangeLastTime = dataChangeLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.build_id
     *
     * @return the value of env.build_id
     *
     * @mbggenerated
     */
    public Long getBuildId() {
        return buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.build_id
     *
     * @param buildId the value for env.build_id
     *
     * @mbggenerated
     */
    public void setBuildId(Long buildId) {
        this.buildId = buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.build_time
     *
     * @return the value of env.build_time
     *
     * @mbggenerated
     */
    public Date getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.build_time
     *
     * @param buildTime the value for env.build_time
     *
     * @mbggenerated
     */
    public void setBuildTime(Date buildTime) {
        this.buildTime = buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.release_version
     *
     * @return the value of env.release_version
     *
     * @mbggenerated
     */
    public Long getReleaseVersion() {
        return releaseVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.release_version
     *
     * @param releaseVersion the value for env.release_version
     *
     * @mbggenerated
     */
    public void setReleaseVersion(Long releaseVersion) {
        this.releaseVersion = releaseVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.release_time
     *
     * @return the value of env.release_time
     *
     * @mbggenerated
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.release_time
     *
     * @param releaseTime the value for env.release_time
     *
     * @mbggenerated
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.auto_release
     *
     * @return the value of env.auto_release
     *
     * @mbggenerated
     */
    public Boolean getAutoRelease() {
        return autoRelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.auto_release
     *
     * @param autoRelease the value for env.auto_release
     *
     * @mbggenerated
     */
    public void setAutoRelease(Boolean autoRelease) {
        this.autoRelease = autoRelease;
    }
}