package com.configx.web.model;

import java.util.Date;

public class Release {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.env_id
     *
     * @mbggenerated
     */
    private Integer envId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.env_name
     *
     * @mbggenerated
     */
    private String envName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.release_status
     *
     * @mbggenerated
     */
    private Byte releaseStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.release_user_code
     *
     * @mbggenerated
     */
    private String releaseUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.release_ip
     *
     * @mbggenerated
     */
    private String releaseIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.release_build_id
     *
     * @mbggenerated
     */
    private Long releaseBuildId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.release_time
     *
     * @mbggenerated
     */
    private Date releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.rollback_user_code
     *
     * @mbggenerated
     */
    private String rollbackUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.rollback_ip
     *
     * @mbggenerated
     */
    private String rollbackIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.rollback_build_id
     *
     * @mbggenerated
     */
    private Long rollbackBuildId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.rollback_time
     *
     * @mbggenerated
     */
    private Date rollbackTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.release_message
     *
     * @mbggenerated
     */
    private String releaseMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release.rollback_message
     *
     * @mbggenerated
     */
    private String rollbackMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.id
     *
     * @return the value of release.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.id
     *
     * @param id the value for release.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.app_id
     *
     * @return the value of release.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.app_id
     *
     * @param appId the value for release.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.app_name
     *
     * @return the value of release.app_name
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.app_name
     *
     * @param appName the value for release.app_name
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.env_id
     *
     * @return the value of release.env_id
     *
     * @mbggenerated
     */
    public Integer getEnvId() {
        return envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.env_id
     *
     * @param envId the value for release.env_id
     *
     * @mbggenerated
     */
    public void setEnvId(Integer envId) {
        this.envId = envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.env_name
     *
     * @return the value of release.env_name
     *
     * @mbggenerated
     */
    public String getEnvName() {
        return envName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.env_name
     *
     * @param envName the value for release.env_name
     *
     * @mbggenerated
     */
    public void setEnvName(String envName) {
        this.envName = envName == null ? null : envName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.release_status
     *
     * @return the value of release.release_status
     *
     * @mbggenerated
     */
    public Byte getReleaseStatus() {
        return releaseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.release_status
     *
     * @param releaseStatus the value for release.release_status
     *
     * @mbggenerated
     */
    public void setReleaseStatus(Byte releaseStatus) {
        this.releaseStatus = releaseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.release_user_code
     *
     * @return the value of release.release_user_code
     *
     * @mbggenerated
     */
    public String getReleaseUserCode() {
        return releaseUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.release_user_code
     *
     * @param releaseUserCode the value for release.release_user_code
     *
     * @mbggenerated
     */
    public void setReleaseUserCode(String releaseUserCode) {
        this.releaseUserCode = releaseUserCode == null ? null : releaseUserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.release_ip
     *
     * @return the value of release.release_ip
     *
     * @mbggenerated
     */
    public String getReleaseIp() {
        return releaseIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.release_ip
     *
     * @param releaseIp the value for release.release_ip
     *
     * @mbggenerated
     */
    public void setReleaseIp(String releaseIp) {
        this.releaseIp = releaseIp == null ? null : releaseIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.release_build_id
     *
     * @return the value of release.release_build_id
     *
     * @mbggenerated
     */
    public Long getReleaseBuildId() {
        return releaseBuildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.release_build_id
     *
     * @param releaseBuildId the value for release.release_build_id
     *
     * @mbggenerated
     */
    public void setReleaseBuildId(Long releaseBuildId) {
        this.releaseBuildId = releaseBuildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.release_time
     *
     * @return the value of release.release_time
     *
     * @mbggenerated
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.release_time
     *
     * @param releaseTime the value for release.release_time
     *
     * @mbggenerated
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.rollback_user_code
     *
     * @return the value of release.rollback_user_code
     *
     * @mbggenerated
     */
    public String getRollbackUserCode() {
        return rollbackUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.rollback_user_code
     *
     * @param rollbackUserCode the value for release.rollback_user_code
     *
     * @mbggenerated
     */
    public void setRollbackUserCode(String rollbackUserCode) {
        this.rollbackUserCode = rollbackUserCode == null ? null : rollbackUserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.rollback_ip
     *
     * @return the value of release.rollback_ip
     *
     * @mbggenerated
     */
    public String getRollbackIp() {
        return rollbackIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.rollback_ip
     *
     * @param rollbackIp the value for release.rollback_ip
     *
     * @mbggenerated
     */
    public void setRollbackIp(String rollbackIp) {
        this.rollbackIp = rollbackIp == null ? null : rollbackIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.rollback_build_id
     *
     * @return the value of release.rollback_build_id
     *
     * @mbggenerated
     */
    public Long getRollbackBuildId() {
        return rollbackBuildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.rollback_build_id
     *
     * @param rollbackBuildId the value for release.rollback_build_id
     *
     * @mbggenerated
     */
    public void setRollbackBuildId(Long rollbackBuildId) {
        this.rollbackBuildId = rollbackBuildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.rollback_time
     *
     * @return the value of release.rollback_time
     *
     * @mbggenerated
     */
    public Date getRollbackTime() {
        return rollbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.rollback_time
     *
     * @param rollbackTime the value for release.rollback_time
     *
     * @mbggenerated
     */
    public void setRollbackTime(Date rollbackTime) {
        this.rollbackTime = rollbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.release_message
     *
     * @return the value of release.release_message
     *
     * @mbggenerated
     */
    public String getReleaseMessage() {
        return releaseMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.release_message
     *
     * @param releaseMessage the value for release.release_message
     *
     * @mbggenerated
     */
    public void setReleaseMessage(String releaseMessage) {
        this.releaseMessage = releaseMessage == null ? null : releaseMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release.rollback_message
     *
     * @return the value of release.rollback_message
     *
     * @mbggenerated
     */
    public String getRollbackMessage() {
        return rollbackMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release.rollback_message
     *
     * @param rollbackMessage the value for release.rollback_message
     *
     * @mbggenerated
     */
    public void setRollbackMessage(String rollbackMessage) {
        this.rollbackMessage = rollbackMessage == null ? null : rollbackMessage.trim();
    }
}