package com.configx.web.model;

import java.util.Date;

public class ReleaseVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_version.number
     *
     * @mbggenerated
     */
    private Long number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_version.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_version.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_version.env_id
     *
     * @mbggenerated
     */
    private Integer envId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_version.env_name
     *
     * @mbggenerated
     */
    private String envName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_version.build_id
     *
     * @mbggenerated
     */
    private Long buildId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_version.release_id
     *
     * @mbggenerated
     */
    private Long releaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_version.rollback_id
     *
     * @mbggenerated
     */
    private Long rollbackId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_version.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_version.number
     *
     * @return the value of release_version.number
     *
     * @mbggenerated
     */
    public Long getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_version.number
     *
     * @param number the value for release_version.number
     *
     * @mbggenerated
     */
    public void setNumber(Long number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_version.app_id
     *
     * @return the value of release_version.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_version.app_id
     *
     * @param appId the value for release_version.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_version.app_name
     *
     * @return the value of release_version.app_name
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_version.app_name
     *
     * @param appName the value for release_version.app_name
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_version.env_id
     *
     * @return the value of release_version.env_id
     *
     * @mbggenerated
     */
    public Integer getEnvId() {
        return envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_version.env_id
     *
     * @param envId the value for release_version.env_id
     *
     * @mbggenerated
     */
    public void setEnvId(Integer envId) {
        this.envId = envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_version.env_name
     *
     * @return the value of release_version.env_name
     *
     * @mbggenerated
     */
    public String getEnvName() {
        return envName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_version.env_name
     *
     * @param envName the value for release_version.env_name
     *
     * @mbggenerated
     */
    public void setEnvName(String envName) {
        this.envName = envName == null ? null : envName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_version.build_id
     *
     * @return the value of release_version.build_id
     *
     * @mbggenerated
     */
    public Long getBuildId() {
        return buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_version.build_id
     *
     * @param buildId the value for release_version.build_id
     *
     * @mbggenerated
     */
    public void setBuildId(Long buildId) {
        this.buildId = buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_version.release_id
     *
     * @return the value of release_version.release_id
     *
     * @mbggenerated
     */
    public Long getReleaseId() {
        return releaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_version.release_id
     *
     * @param releaseId the value for release_version.release_id
     *
     * @mbggenerated
     */
    public void setReleaseId(Long releaseId) {
        this.releaseId = releaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_version.rollback_id
     *
     * @return the value of release_version.rollback_id
     *
     * @mbggenerated
     */
    public Long getRollbackId() {
        return rollbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_version.rollback_id
     *
     * @param rollbackId the value for release_version.rollback_id
     *
     * @mbggenerated
     */
    public void setRollbackId(Long rollbackId) {
        this.rollbackId = rollbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_version.create_time
     *
     * @return the value of release_version.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_version.create_time
     *
     * @param createTime the value for release_version.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}