package com.configx.web.model;

import java.util.Date;

public class WebhookLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.webhook_id
     *
     * @mbggenerated
     */
    private Integer webhookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.content_type
     *
     * @mbggenerated
     */
    private String contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.secret
     *
     * @mbggenerated
     */
    private String secret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.event_type
     *
     * @mbggenerated
     */
    private Integer eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.event_name
     *
     * @mbggenerated
     */
    private String eventName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.event_params
     *
     * @mbggenerated
     */
    private String eventParams;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.request_params
     *
     * @mbggenerated
     */
    private String requestParams;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.request_headers
     *
     * @mbggenerated
     */
    private String requestHeaders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.status_code
     *
     * @mbggenerated
     */
    private Integer statusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.response_headers
     *
     * @mbggenerated
     */
    private String responseHeaders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.request_body
     *
     * @mbggenerated
     */
    private String requestBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.response_body
     *
     * @mbggenerated
     */
    private String responseBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_log.error_msg
     *
     * @mbggenerated
     */
    private String errorMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.id
     *
     * @return the value of webhook_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.id
     *
     * @param id the value for webhook_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.app_id
     *
     * @return the value of webhook_log.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.app_id
     *
     * @param appId the value for webhook_log.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.app_name
     *
     * @return the value of webhook_log.app_name
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.app_name
     *
     * @param appName the value for webhook_log.app_name
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.webhook_id
     *
     * @return the value of webhook_log.webhook_id
     *
     * @mbggenerated
     */
    public Integer getWebhookId() {
        return webhookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.webhook_id
     *
     * @param webhookId the value for webhook_log.webhook_id
     *
     * @mbggenerated
     */
    public void setWebhookId(Integer webhookId) {
        this.webhookId = webhookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.name
     *
     * @return the value of webhook_log.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.name
     *
     * @param name the value for webhook_log.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.url
     *
     * @return the value of webhook_log.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.url
     *
     * @param url the value for webhook_log.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.content_type
     *
     * @return the value of webhook_log.content_type
     *
     * @mbggenerated
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.content_type
     *
     * @param contentType the value for webhook_log.content_type
     *
     * @mbggenerated
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.secret
     *
     * @return the value of webhook_log.secret
     *
     * @mbggenerated
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.secret
     *
     * @param secret the value for webhook_log.secret
     *
     * @mbggenerated
     */
    public void setSecret(String secret) {
        this.secret = secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.event_type
     *
     * @return the value of webhook_log.event_type
     *
     * @mbggenerated
     */
    public Integer getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.event_type
     *
     * @param eventType the value for webhook_log.event_type
     *
     * @mbggenerated
     */
    public void setEventType(Integer eventType) {
        this.eventType = eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.event_name
     *
     * @return the value of webhook_log.event_name
     *
     * @mbggenerated
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.event_name
     *
     * @param eventName the value for webhook_log.event_name
     *
     * @mbggenerated
     */
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.create_time
     *
     * @return the value of webhook_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.create_time
     *
     * @param createTime the value for webhook_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.event_params
     *
     * @return the value of webhook_log.event_params
     *
     * @mbggenerated
     */
    public String getEventParams() {
        return eventParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.event_params
     *
     * @param eventParams the value for webhook_log.event_params
     *
     * @mbggenerated
     */
    public void setEventParams(String eventParams) {
        this.eventParams = eventParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.request_params
     *
     * @return the value of webhook_log.request_params
     *
     * @mbggenerated
     */
    public String getRequestParams() {
        return requestParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.request_params
     *
     * @param requestParams the value for webhook_log.request_params
     *
     * @mbggenerated
     */
    public void setRequestParams(String requestParams) {
        this.requestParams = requestParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.request_headers
     *
     * @return the value of webhook_log.request_headers
     *
     * @mbggenerated
     */
    public String getRequestHeaders() {
        return requestHeaders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.request_headers
     *
     * @param requestHeaders the value for webhook_log.request_headers
     *
     * @mbggenerated
     */
    public void setRequestHeaders(String requestHeaders) {
        this.requestHeaders = requestHeaders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.status_code
     *
     * @return the value of webhook_log.status_code
     *
     * @mbggenerated
     */
    public Integer getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.status_code
     *
     * @param statusCode the value for webhook_log.status_code
     *
     * @mbggenerated
     */
    public void setStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.response_headers
     *
     * @return the value of webhook_log.response_headers
     *
     * @mbggenerated
     */
    public String getResponseHeaders() {
        return responseHeaders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.response_headers
     *
     * @param responseHeaders the value for webhook_log.response_headers
     *
     * @mbggenerated
     */
    public void setResponseHeaders(String responseHeaders) {
        this.responseHeaders = responseHeaders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.request_body
     *
     * @return the value of webhook_log.request_body
     *
     * @mbggenerated
     */
    public String getRequestBody() {
        return requestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.request_body
     *
     * @param requestBody the value for webhook_log.request_body
     *
     * @mbggenerated
     */
    public void setRequestBody(String requestBody) {
        this.requestBody = requestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.response_body
     *
     * @return the value of webhook_log.response_body
     *
     * @mbggenerated
     */
    public String getResponseBody() {
        return responseBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.response_body
     *
     * @param responseBody the value for webhook_log.response_body
     *
     * @mbggenerated
     */
    public void setResponseBody(String responseBody) {
        this.responseBody = responseBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_log.error_msg
     *
     * @return the value of webhook_log.error_msg
     *
     * @mbggenerated
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_log.error_msg
     *
     * @param errorMsg the value for webhook_log.error_msg
     *
     * @mbggenerated
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }
}