package com.configx.web.model;

public class WebhookEventParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_event_param.webhook_id
     *
     * @mbggenerated
     */
    private Integer webhookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_event_param.event_type
     *
     * @mbggenerated
     */
    private Integer eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_event_param.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webhook_event_param.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_event_param.webhook_id
     *
     * @return the value of webhook_event_param.webhook_id
     *
     * @mbggenerated
     */
    public Integer getWebhookId() {
        return webhookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_event_param.webhook_id
     *
     * @param webhookId the value for webhook_event_param.webhook_id
     *
     * @mbggenerated
     */
    public void setWebhookId(Integer webhookId) {
        this.webhookId = webhookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_event_param.event_type
     *
     * @return the value of webhook_event_param.event_type
     *
     * @mbggenerated
     */
    public Integer getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_event_param.event_type
     *
     * @param eventType the value for webhook_event_param.event_type
     *
     * @mbggenerated
     */
    public void setEventType(Integer eventType) {
        this.eventType = eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_event_param.name
     *
     * @return the value of webhook_event_param.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_event_param.name
     *
     * @param name the value for webhook_event_param.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webhook_event_param.value
     *
     * @return the value of webhook_event_param.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webhook_event_param.value
     *
     * @param value the value for webhook_event_param.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value;
    }
}